#%RAML 0.8
title: Trello API integration
version: 1.0
baseUri: http://win7-64-vm:9905/trello_int
/export:
  get:
    description: <<get the contents of your Trello account>>
    responses:
      200:
        body:
          application/json: